steps:
  # Frontend 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'smart-did-frontend:test'
      - '-f'
      - 'Dockerfile.frontend'
      - '.'
    id: 'build-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
