/**
 * Worker 내부에서 ../shared/types 로 참조 시 사용
 * @smart-did/shared의 pipeline 타입들을 재export.
 * VideoGenerationResult는 pipeline 결과용으로 PipelineJobResult를 별칭 제공.
 */
export type { PipelineJobResult as VideoGenerationResult } from '@smart-did/shared';
export {
  type SceneNumber,
  type SceneType,
  type JobStatus,
  type QCStatus,
  type GenerationMode,
  type VideoGenerationRequest,
  type VideoGenerationJob,
  type SceneResult,
  type SceneScript,
  type Anchor,
  type StyleSignature,
  type TypographyPlan,
  type StoryboardPlan,
  type SceneStoryboard,
  type Keyframe,
  type SafetyConstraints,
  type QCReport,
  type TypographyQCResult,
  type ConsistencyQCResult,
  type SafetyQCResult,
  type VideoScoreResult,
  type CostReport,
  type GeminiProvider,
  type StorageProvider,
  type CacheEntry,
  type BookCandidate,
  type BookCandidateScore,
  type BookCharacter,
  type PlotBeat,
  type BookFacts,
  type ArtDirection,
  type VisualAnchors,
  type StyleBible,
  type SceneScriptV2,
  type ScenePlan,
  type RetryStage,
  type SceneRetryState,
  type RetryLimits,
  type HierarchicalRetryState,
  type RetryResult,
  type VideoGenerationJobV2,
  type SceneResultV2,
} from '@smart-did/shared';
